services:
  cloudflared:
    image: cloudflare/cloudflared:2026.8.3
    container_name: cloudflared
    command: tunnel run
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml
      - ~/.cloudflared:/etc/cloudflared
    restart: unless-stopped
    networks:
      - lab-net

networks:
  lab-net:
    external: true
