services:
  minecraft:
    image: itzg/minecraft-server:java25
    container_name: minecraft
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mc-health"]
      interval: 30s
      timeout: 10s
      retries: ${HEALTHCHECK_RETRIES}
    tty: true
    stdin_open: true
    env_file:
      - ../.env

    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: "26.1.2"

      MEMORY: 4G

      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}

      ONLINE_MODE: "true"
      MOTD: "charlie kirk"

      DIFFICULTY: "normal"
      MAX_PLAYERS: 10

      MODE: survival
      DEFAULT_GAMEMODE: survival

      OPS: "Iron_ore_"

    volumes:
      - ./data:/data

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.17
    restart: unless-stopped
    network_mode: service:minecraft
    env_file:
      - ../.env

    depends_on:
      - minecraft
    healthcheck:
      test: ["CMD-SHELL", "kill -0 1"]
      interval: 30s
      timeout: 5s
      retries: ${HEALTHCHECK_RETRIES}
