beakers:
  nextcloud:
    aliases: [nas]
    autostart: true
    depends_on: []
  cloudflared:
    aliases: [cloudflare, tunnel]
    autostart: true
    depends_on: [nextcloud]
  minecraft:
    aliases: []
    autostart: false
    depends_on: []