restart_max_retries: 5

beakers:
  nextcloud:
    aliases: [nas]
    autostart: true
    allow_restart: true
    depends_on: [ofelia]
  cloudflared:
    aliases: [cloudflare, tunnel]
    autostart: true
    allow_restart: true
    wait_seconds: 5
    depends_on: [nextcloud, ofelia]
  minecraft:
    aliases: []
    autostart: false
    allow_restart: true
    depends_on: [ofelia]
  ofelia:
    aliases: []
    autostart: true
    allow_restart: false
    depends_on: []