from pathlib import Path

LAB_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = Path(__file__).with_name("cli_config.yaml")
NETWORK = "lab-net"
COMPOSE_ENV_FILE = LAB_ROOT / ".env"
NOTIFICATION_LOG = LAB_ROOT / "lab_notifications.log"
HEALTH_POLL_INTERVAL = 2
HEALTHCHECK_SAFETY_CAP_SECONDS = 600
HIGH_TOLERANCE_HEALTHCHECK_RETRIES = 30
WARNING_DISK_PERCENT = 90
WARNING_MEMORY_PERCENT = 90
WARNING_TEMPERATURE_CELSIUS = 80
