from pathlib import Path

LAB_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = Path(__file__).with_name("cli_config.yaml")
NETWORK = "lab-net"
COMPOSE_ENV_FILE = LAB_ROOT / ".env"
NOTIFICATION_LOG = LAB_ROOT / "lab_notifications.log"
LOW_TOLERANCE_HEALTH_TIMEOUT = 40
HIGH_TOLERANCE_HEALTH_TIMEOUT = 300
LOW_TOLERANCE_HEALTH_POLL_INTERVAL = 2
HIGH_TOLERANCE_HEALTH_POLL_INTERVAL = 10
HIGH_TOLERANCE_HEALTHCHECK_RETRIES = 30
